version: "3"

services:
  penger-party:
    container_name: "penger-party"
    restart: always
    image: "node"
    ports:
      - "6912:6969"
      - "4242:4242"
    volumes:
      - ".:/app"
    working_dir: "/app"
    command: "node /app/server.js"
