version: "3"

services:
  web:
    container_name: "web"
    image: "node"
    ports:
      - "6969:6969"
      - "4242:4242"
    volumes:
      - ".:/app"
    working_dir: "/app"
    command: "node /app/server.js"
